### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 100petr** [J3fftw1/SlimeXpansion#13]
## Description (Required)

Error on Startup server

## Server Log / Error Report

 
https://pastebin.com/iH1dpcK8

## Environment (Required)

http://prntscr.com/rsw4wy
 - Minecraft Version: 1.15.2
 - Slimefun Version: 477 (git 156683f3)
 - CS-CoreLib Version: 83 (git 8081bb4f)
 - SlimeExpansion Version: 12 (git cbf20)

**Comment by J3fftw1** [comment]
update
