### ISSUE TITLE
Geo Scanner

### ISSUE THREAD

**Issue by Sashavovo** [J3fftw1/SlimeXpansion#18]
## Description (Required)
Just Geo scan
## Steps to reproduce the Issue (Required)
Just Geo scan
## Expected behavior (Required)
🗡️ 
## Server Log / Error Report
https://pastebin.com/yk5HXB13
## Environment (Required)
 - Minecraft Version: 1.15.2
 - Slimefun Version: #470
 - CS-CoreLib Version: #85
 - SlimeExpansion Version: #15

**Comment by WalshyDev** [comment]
You have a corrupted jar. Either way, SlimeXpansion is no longer supported. Please use [LiteXpansion](https://github.com/J3fftw1/LiteXpansion) instead.

**Comment by Sashavovo** [comment]
TheBusyBiscuit
banned me on github and the discord channel, but I found a bug.
CommandOverride - #15
Doesn’t withdraw money when you use a command.
Only when the amount you have is less than what is specified in the configs, then the command does not occur.

**Comment by J3fftw1** [comment]
> TheBusyBiscuit
> banned me on github and the discord channel, but I found a bug.
> CommandOverride - #15
> Doesn’t withdraw money when you use a command.
> Only when the amount you have is less than what is specified in the configs, then the command does not occur.
> 
> \\\\\\\\\\\
> I'm sorry that I am writing this here, but I have not found any more way to send this somehow (

how is this slimexpansion
