### ISSUE TITLE
Fatal Error When Loading

### ISSUE THREAD

**Issue by MrWardy** [J3fftw1/SlimeXpansion#19]
## Description (Required)
An error occurs when trying to load, and spigot says the plugin is loaded but nothing comes up in the slimefun guide.

I also have a side question, is LiteXpansion separate from SlimeXpansion in terms of features? Are there missing features in LiteXpansion that are in SlimeXpansion?

## Steps to reproduce the Issue (Required)
I'm not sure how to reproduce it.

## Expected behavior (Required)
For there to be no error and for there to be things in the slimefun guide

## Server Log / Error Report
Specific Error: https://pastebin.com/sV0JUxMd
Full Console Log: https://pastebin.com/bbNWNgFB

## Environment (Required)
Versions: https://lunus.xyz/q2QLwX.png

 - Minecraft Version: 1.15.2
 - Slimefun Version: vDEV 497
 - CS-CoreLib Version: vDEV 87
 - SlimeExpansion Version: vDEV 15

**Comment by WalshyDev** [comment]
SlimeXpansion is no longer supported. Please use [LiteXpansion](https://github.com/J3fftw1/LiteXpansion/) instead.

If you'd like to suggest something new to LiteXpansion then make a [new issue here](https://github.com/J3fftw1/LiteXpansion/issues)
