### ISSUE TITLE
Thorium is not radioactive

### ISSUE THREAD

**Issue by TheBusyBiscuit** [J3fftw1/SlimeXpansion#6]
## Description (Required)

Thorium is registered as a normal "SlimefunItem" but has been given a lore that would indicate it's radioactive.
You should create a new class for Thorium and implement the interface "Radioactive" to make it actually radiate though.

You can clearly see that it was registered as a SlimefunItem here:
https://github.com/J3fftw1/SlimeXpansion/blob/master/src/me/john000708/slimexpansion/SlimeXpansion.java#L248-L251

## Steps to reproduce the Issue (Required)

1. Open the file
2. Open your eyes, look up to the skies and see...
3. "I'm just a poor boy, I need no sympathy"
4. "Because I'm easy come, easy go, little high, little low. Anyway the wind blows. Doesn't relly matter to me, to me..."

## Expected behavior (Required)

Thorium to be registered with an implementation of the interface "Radioactive".

## Server Log / Error Report

Not applicable

## Environment (Required)

 - Minecraft Version: latest lul
 - Slimefun Version: latest lul
 - CS-CoreLib Version: latest lul
 - SlimeExpansion Version: latest lul

(I looked at the code to check whether the latest build will break this again, it shouldn't and it won't but I noticed that while i was scrolling by, so I don't really have versions to provide other than maybe c4ceb85083a8aac6f3020236b18c9d43985469db )

**Comment by J3fftw1** [comment]
Please show version
Latest isnt ur version
