### ISSUE TITLE
Cannot enable SlimeXpansion DEV10

### ISSUE THREAD

**Issue by MlgmXyysd** [J3fftw1/SlimeXpansion#7]
## Description (Required)
Error when enable SlimeXpansion

## Steps to reproduce the Issue (Required)

Put CS-Corelib, Slimefun, SlimeXpansion and other addons

Start the server

## Expected behavior (Required)

SlimeXpansion enabled

## Server Log / Error Report
https://pastebin.com/C1BTLSxQ

## Environment (Required)

DyedBackpacks vDEV - 4 (git 99945ff4)
SlimefunOreChunks vDEV - 7 (git 1edd355c)
HotbarPets vDEV - 26 (git 7489ae00)
ExtraGear vDEV - 7 (git 9e953653)
SlimefunLuckyBlocks vDEV - 19 (git 9dbab303)
ExoticGarden vDEV - 35 (git deec898a)
Barrels vDEV - 11 (git abecba9c)
ElectricSpawners vDEV - 9 (git 9cf22acb)
ExtraHeads vDEV - 12 (git 51e97ace)
SoulJars vDEV - 12 (git 6b475952)
MobCapturer vDEV - 5 (git b20f13ca)
SlimyTreeTaps vDEV - 9 (git 55c9996f)
PrivateStorage vDEV - 11 (git b064863b)
ColoredEnderChests vDEV - 10 (git 5dcddabb)
ChestTerminal vDEV - 26 (git 5b0db2b7)

 - Minecraft Version: Paper 1.15.2
 - Slimefun Version: vDEV - 458 (git eed8cb4e)
 - CS-CoreLib Version: vDEV - 83 (git 8081bb4f)
 - SlimeExpansion Version: vDEV - 10 (git c4ceb850)

**Comment by PhantumOne** [comment]
I am also getting the same error in 1.5.2; I did fix the GOLD_HELMET and SIGN issue in the config.yml. I changed them to GOLDEN_HELMET and changed SIGN to ACACIA_SIGN and added the other 5 types of wood signs.

Hope this gets fixed soon.

**Comment by MlgmXyysd** [comment]
> I am also getting the same error in 1.5.2; I did fix the GOLD_HELMET and SIGN issue in the config.yml. I changed them to GOLDEN_HELMET and changed SIGN to ACACIA_SIGN and added the other 5 types of wood signs.
> 
> I am running these SlimeFun Addons updated to current versions:
> 
> ExoticGarden
> ColoredEnderChests
> LuckyBlocks
> HotbarPets
> SoulJars
> ElectricSpawners
> PrivateStorage
> ChestTerminal
> Barrels
> ExtraGear
> ExtraHeads
> SlimefunOreChunks
> DyedBackpacks
> SlimyTreeTaps
> MobCapturer
> SlimeXpansion
> SoundMuffler
> ClayTech
> EmeraldEnchants
> PlaceholderAPI
> WhatIsThis
> 
> Hope this gets fixed soon.

I removed these item, but crash again java.lang.AbstractMethodError: Method me/john000708/slimexpansion/SlimeXpansion$1.getCapacity()I is abstract

**Comment by WalshyDev** [comment]
Fixed in [build 12](https://thebusybiscuit.github.io/builds/J3fftw1/SlimeXpansion/master/#12)
