### ISSUE TITLE
Error log on start up

### ISSUE THREAD

**Issue by yumjunstar** [J3fftw1/SlimeXpansion#9]
## Description (Required)

Just error log on start up
## Steps to reproduce the Issue (Required)
1. install extra gear-dev-7, extra head-dev-12, slimefun4-RC-9, CS-CORELIB-1.6.2, EXOTIC GARDEN DEV-37, SlimefunXpansion-dev-10
2. and download paper-131 1.15.2 
3. startup
## Expected behavior (Required)
error log

## Server Log / Error Report
https://paste.gg/p/anonymous/c8875c0722bb4b5bada085d9c4fd27d4

## Environment (Required)
extra gear-dev-7
extra head-dev-12
slimefun4-RC-9
CS-CORELIB-1.6.2
EXOTIC GARDEN DEV-37
SlimefunXpansion-dev-10
paper-131 -1.15.2

**Comment by WalshyDev** [comment]
Fixed in [build 12](https://thebusybiscuit.github.io/builds/J3fftw1/SlimeXpansion/master/#12)
